### ISSUE TITLE
OpenSSL 1.1 support

### ISSUE THREAD

**Issue by jbasney** [globus/gsi-openssh#14]
OpenSSH 7.2 does not support OpenSSL 1.1 ([openssh-unix-dev](https://lists.mindrot.org/pipermail/openssh-unix-dev/2016-February/034834.html)).
OpenSSL 1.1.0 was released 25-Aug-2016.
Presumably OpenSSH 7.3 supports OpenSSL 1.1 (need to verify), so updating GSI-OpenSSH to OpenSSH 7.3 will hopefully mostly address this issue.
However #13 also must be resolved as part of OpenSSL 1.1 support in GSI-OpenSSH.

**Comment by jbasney** [comment]
Bad news: OpenSSH 7.3 also does not support OpenSSL 1.1.x ([openssh-unix-dev](https://lists.mindrot.org/pipermail/openssh-unix-dev/2016-July/035206.html)).
Looks like this will not be resolved until OpenSSH 7.4 at the earliest.

**Comment by jbasney** [comment]
Note an initial announcement about this went out to [gsi-openssh-user](http://lists.globus.org/pipermail/gsi-openssh-user/2016-September/000136.html) on Sep 14 2016 and it's being discussed on [gt-dev](http://lists.globus.org/pipermail/gt-dev/2016-October/002211.html).

There's a [pull request](https://github.com/openssh/openssh-portable/pull/48) for OpenSSL 1.1 support in OpenSSH, announced on [openssh-unix-dev](https://lists.mindrot.org/pipermail/openssh-unix-dev/2016-September/035378.html).

**Comment by jbasney** [comment]
Fedora Rawhide is using a variation on the patch from September for OpenSSL 1.1.0 support. See [openssh-unix-dev](https://lists.mindrot.org/pipermail/openssh-unix-dev/2016-November/035454.html).

**Comment by ysvenkat** [comment]
Support for both old and new MICs introduced in the latest globus-gssapi-gsi now supported in GSI-OpenSSH 7.1p2g:
https://github.com/globus/gsi-openssh/releases/tag/7.1p2g

**Comment by carsten-AEI** [comment]
Chiming in here, as Debian introduced 1.1.0c into testing on 2016-11-28 and not quite surprisingly gsissh stopped working on my laptop. Not sure if this helps you or I just re-iterate on common developer knowledge, `configure` does not work sanely anymore due to missing `SSLeay()` for version comparison:
```
configure:32863: checking whether OpenSSL's headers match the library
configure:32898: gcc -o conftest -g -O2 -Wall -Wpointer-arith -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -ftrapv -fno-builtin-memset -fstack-protector-strong -fPIE   -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -fstack-protector-strong -pie conftest.c -lcrypto -ldl -lutil -lz -lnsl  >&5
conftest.c: In function 'main':
conftest.c:219:3: warning: implicit declaration of function 'exit' [-Wimplicit-function-declaration]
   exit(SSLeay() == OPENSSL_VERSION_NUMBER ? 0 : 1);
   ^~~~
conftest.c:219:3: warning: incompatible implicit declaration of built-in function 'exit'
conftest.c:219:3: note: include '<stdlib.h>' or provide a declaration of 'exit'
conftest.c:219:8: warning: implicit declaration of function 'SSLeay' [-Wimplicit-function-declaration]
   exit(SSLeay() == OPENSSL_VERSION_NUMBER ? 0 : 1);
        ^~~~~~
/tmp/ccrJsFy1.o: In function `main':
/tmp/gsi-openssh/conftest.c:219: undefined reference to `SSLeay'
```

Working around that check with `--without-openssl-header-check` ends up with a build failure:

```
gcc -g -O2  -Wall -Wpointer-arith -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -ftrapv -fno-builtin-memset -fstack-protector-strong -fPIE  -I. -I.. -I. -I./..  -I/usr/include/editline -DHAVE_CONFIG_H -c bsd-closefrom.c
In file included from ssh_api.h:26:0,
                 from ssh_api.c:21:
cipher.h:69:17: error: field ‘evp’ has incomplete type
  EVP_CIPHER_CTX evp;
                 ^~~
Makefile:156: recipe for target 'ssh_api.o' failed
```

That's where I stopped looking for now. Unless you have a suggestion how to get gsissh working again with openssl 1.1 I guess I need to resort to "old-fashioned" ssh somehow ;)

**Comment by jbasney** [comment]
Thanks @carsten-AEI for the info on Debian Testing (Stretch).

GSI-OpenSSH inherits the OpenSSL 1.1 build problems from OpenSSH. Once an OpenSSH release that supports OpenSSL 1.1 is made available, we'll update GSI-OpenSSH to use it.

According to [Debian Bug 827061](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827061), "openssl/1.0.2 will remaining in stretch and will be available to the subset of packages that are infeasible to port to openssl/1.1 in time for stretch." However, I think the Globus GSI libraries have already updated to OpenSSL 1.1 on Debian Stretch, so GSI-OpenSSH is stuck in the middle until OpenSSH is updated to support OpenSSL 1.1.

I don't think it makes sense for GSI-OpenSSH to incorporate (and maintain/support) the 1000+ line proposed OpenSSH [patch](https://github.com/openssh/openssh-portable/pull/48) for OpenSSL 1.1 compatibility in advance of an official OpenSSH release that supports OpenSSL 1.1, even though some of the Linux distros are starting to use that OpenSSH patch in their testing releases.

**Comment by jbasney** [comment]
OpenSSH 7.4 won't work with OpenSSL 1.1: [openssh-unix-dev](https://lists.mindrot.org/pipermail/openssh-unix-dev/2016-December/035539.html)

**Comment by jbasney** [comment]
While we wait for OpenSSH portable to support OpenSSL 1.1, I wonder if compiling GSI-OpenSSH with [OPENSSL=no](http://article.gmane.org/gmane.os.openbsd.cvs/130612) would help to eliminate the compatibility issue, since the direct dependency between OpenSSH and OpenSSL is now optional. Of course the GSI libraries would still use OpenSSL, but they've been ported to OpenSSL 1.1 already.

**Comment by ysvenkat** [comment]
OpenSSH still seems to support without-openssl on an experimental basis only:

AC_ARG_WITH([openssl],
	[  --without-openssl       Disable use of OpenSSL; use only limited internal crypto **EXPERIMENTAL** ],
	[  if test "x$withval" = "xno" ; then
		openssl=no
		ssh1=no
	   fi
	]
)
AC_MSG_CHECKING([whether OpenSSL will be used for cryptography])
if test "x$openssl" = "xyes" ; then
	AC_MSG_RESULT([yes])
	AC_DEFINE_UNQUOTED([WITH_OPENSSL], [1], [use libcrypto for cryptography])
else
	AC_MSG_RESULT([no])
fi

On configuring --without-openssl

PKG_CONFIG_PATH=/usr/lib64/pkgconfig ./configure --prefix=$HOME/gsi-openssh.install --with-pam --with-nerscmod --with-tcp-wrappers --with-gsi --without-openssl 2>&1 | tee -a log.configure6

compilation fails due to dependency on openssl/dh.h and very likely others:

gcc -g -O2  -Wall -Wpointer-arith -Wsign-compare -Wformat-security -Wno-pointer-sign -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -ftrapv -fno-builtin-memset -fstack-protector-all -fPIE  -g -O2  -I/usr/include/globus -I. -I.  -D_PATH_SSH_ASKPASS_DEFAULT=\"/home/ysvenkat/gsi-openssh.install/libexec/ssh-askpass\" -DGSISSHDIR="\"/home/ysvenkat/gsi-openssh.install/etc\"" -D_PATH_SSH_PIDDIR=\"/var/run\" -D_PATH_PRIVSEP_CHROOT_DIR=\"/var/empty\" -DHAVE_CONFIG_H -c kexgssc.c -o kexgssc.o
kexgssc.c: In function ‘kexgss_client’:
kexgssc.c:174: error: dereferencing pointer to incomplete type
kexgssc.c:256: warning: implicit declaration of function ‘DH_size’
kexgssc.c:258: warning: implicit declaration of function ‘DH_compute_key’
kexgssc.c:281: error: dereferencing pointer to incomplete type
kexgssc.c:296: error: dereferencing pointer to incomplete type
kexgssc.c:296: error: dereferencing pointer to incomplete type
kexgssc.c:297: error: dereferencing pointer to incomplete type
kexgssc.c:316: warning: implicit declaration of function ‘DH_free’
make: *** [kexgssc.o] Error 1
[ysvenkat@ysvenkat gsi-openssh]$

**Comment by tpdownes** [comment]
I don't really understand the issue here. At least for Debian 9. libssl1.0-dev and libssl1.0.2 are both things that exist and its how the [vanilla openssh-server package](https://packages.debian.org/stretch/openssh-server) is compiled.

Practically speaking, isn't this a non-issue?

**Comment by carsten-AEI** [comment]
Unfortunately, it is - at least to my understanding. gsissh on Debian Stretch broke when the underlying globus libraries were recompiled against openssl 1.1 and the `gsi` part of gsissh seems to use that one. Thus, the ssh part now also needs to support openssl 1.1.

**Comment by tpdownes** [comment]
When I look at the dependency chain of the server and client packages, I see a direct dependency on `libssl` and an indirect dependency on libssl via `libglobus-gssapi-gsi4`.

Now I know that the 2 debian libssl packages can live side-by-side. So that program A can use 1.0.2 and program B can use 1.1.0. But, let's assume that you are right and that the whole dependency chain for a single program must pick a single version. Doesn't this mean the problem of gsi-openssh reduces to re-packaging libglobus-gssapi-gsi4 so that it builds against libssl1.0.2?

Taking a more global perspective of the globus tools, it would mean repackaging the output of something like `apt-cache rdepends libssl1.1.0 | grep globus`?

**Comment by jbasney** [comment]
I agree that linking against OpenSSL 1.0 is the current required work-around, but GSI-OpenSSH can't stay on OpenSSL 1.0 forever. Eventually GSI-OpenSSH needs to support OpenSSL 1.1.

**Comment by tpdownes** [comment]
Well, forever, is a long time. But there's 2 issues:

* openssl 1.1 support for the long haul, much of which is dependent on the much larger openssh project
* the other of supporting the operating systems we have right now, with well-defined horizons for their own support and a well-defined horizon of support for openssl 1.0.2 upstream

So, for the 2nd issue... what, specifically, would you suggest for getting gsisshd working against openssl 1.0.2 on Debian 9? Is it the case that we also have to re-compile the whole dependency chains as shown by "apt-cache depends gsi-openssh-server" (and on down the tree)?

**Comment by jbasney** [comment]
Yes, gsisshd and all its shared library dependencies must be compiled/linked using the same openssl library version. It's especially important in this case since the openssl ABI changed so drastically in 1.1.0.

**Comment by carsten-AEI** [comment]
Just checked with `debtree` and it seems that only various `globus` libraries are linked against ssl 1.1, i.e. a short gap solution would be to rebuild those.
![gsi-openssh-clients](https://cloud.githubusercontent.com/assets/16311083/22771315/461b77d2-ee96-11e6-8bf4-047b7ada0a79.png)

**Comment by tpdownes** [comment]
Although I appreciate the problem of openssl 1.1.0 support, I do think the more useful way of approaching this problem is how to build gsisshd on specific platforms. I see the following approaches

* rebuild (Carsten's subset of?) globus libraries against 1.0.2 ourselves and come up with simple-to-communicate-to-users way of ensuring they are used before those from stretch (which is now frozen)
* incorporate one of the upstream patches (e.g. Fedora) to openssh for a few releases

I do also see an alternative approach altogether: turn this functionality into a PAM module. Wouldn't that avoid a lot of headache? I have previously made use of pam_ssh_agent_auth with sudo. It allowed me to grant sudo access based upon a particular key being unlocked in an ssh-agent. I imagine it would not be crazy difficult to do a similar thing based upon certificate verification and a grid-mapfile.

Otherwise, I think the 2 options above are what we have to choose from and we must, simply, choose 1. I would choose option (2) for better or worse.

**Comment by carsten-AEI** [comment]
I think the safe option for us (LIGO) would be to rebuild the globus libraries against ssl 1.0 with a version number which is just a little bit higher than the Debian stretch version - that way our versions would be installed by us and our users and if there were a security update during the Stretch cycle we would be alerted rapidly.

Patching a security relevant system such as ssh is something I would try to avoid as I would have no idea to prove that the patch and/or our way of patching does the right thing(TM), especially not triggering something like https://xkcd.com/221/ ;)

**Comment by tpdownes** [comment]
We're already patching openssh with security-related stuff, it's just a question of how much. The openssl 1.1.0 patch is being included in updates to the current release (25) of Fedora. So, it's not bat**** crazy to incorporate those patches.

I agree with your conclusion regarding the safe move for LIGO in the short-term. I think it would be interesting if we could get a working gsissh client package for folks.

**Comment by jbasney** [comment]
For what it's worth, one of the benefits of linking with OpenSSL 1.0 for as long as possible is to get the backwards/forwards compatibility provided by the fix for #13. Linking with OpenSSL 1.1 forces use of the new MIC and breaks interoperability with older gsissh clients and servers.

I propose that @ysvenkat request the current maintainers of the Globus libraries to use OpenSSL 1.0 for now so it's not necessary for LIGO to maintain separate packages.

**Comment by ysvenkat** [comment]
FYI, Mattias is advising against linking with non-default OpenSSL versions.

----------------------------
fre 2017-02-10 klockan 23:24 +0000 skrev Yekkirala, Venkatesh Sri:
Joe and Mattias,
 
As you are aware, starting with release 7.1p2g, GSI-OpenSSH performs
mechanism OID negotiation as noted in:
 
https://github.com/globus/gsi-openssh/issues/13
 
This enables both OpenSSL 1.1 and OpenSSL 1.0 based GSI-OpenSSH
clients to be able to connect to a GSI-OpenSSH 7.1p2g server linked
to OpenSSL 1.0. As well, GSI-OpenSSH 7.1p2g clients linked to OpenSSL
1.0 can connect to both old and new OpenSSL 1.1 linked GSI-OpenSSH
servers.
 
Per the discussion on the below issue as well, Jim recommends linking
Globus libraries and GSI-OpenSSH to OpenSSL 1.0 compat libraries on
new Debian 9/Stretch, Fedora 26 and others that move to OpenSSL 1.1
to enable maximum interoperability in the interim while we wait for
OpenSSH to become compatible to OpenSSL 1.1.
 
https://github.com/globus/gsi-openssh/issues/14
 
Thanks,
 
venkat

Years ago, the Globus Toolkit used to have a component called globus-
openssl, that contained a copy of the openssl sources. The default
build of the toolkit at the time built its own openssl library from
these sources and linked its other components to it. This was causing
lots of problems.

The Globus Toolkit is a toolkit, i.e. it is a set of libraries and
services on top of which other higher level services are built. These
higher level services often use not only the libraries from the Globus
Toolkit, but many other libraries available on the system as well.
These other libraries are part of the distribution and are properly
integrated with it and when they in turn depend on other libraries they
depend on the version of the libraries that are in the distribution.
Since a lot of libraries eventually down their dependency chain depend
on openssl, they will depend on the default openssl version in the
distribution.

If the Globus Toolkit would use its own openssl library different from
the default version in the distribution it would mean that many things
that builds on top of the toolkit would end up with two different
versions of the openssl library loaded in the same process, which would
lead to lots and lots of problems.

There was a reason why in the early days, many users threw out the
globus-openssl component and replaced it with a dummy package
translating the dependencies to dependencies on the openssl package
provided by the distribution. Eventually the globus-openssl component
was thrown out also of the Globus Toolkit sources.

You are now suggesting to once again use a non-default version of the
openssl library to build the Globus Toolkit. This would result in the
same problems as the old globus-openssl component had, and make the
toolkit unusable for many of it users.

Please do not do this!!!

	Mattias

**Comment by tpdownes** [comment]
OpenSSL 1.0.2 is a fully-packaged and supported version of OpenSSL on Debian 8. Many packages, including openssh, use it just fine. It's not a random choice - it's one Debian deliberately makes available for this very purpose.

**Comment by ysvenkat** [comment]
There's a pre-release available at the below link of a version that includes the Fedora OpenSSL 1.1 patch. I would appreciate a test on Stretch and other pertinent platforms. Thanks.

https://github.com/globus/gsi-openssh/releases/tag/7.3p1

**Comment by ysvenkat** [comment]
Update: I find the above pre-release doesn't yet compile with OpenSSL 1.1 because the HPN patch doesn't yet support OpenSSL 1.1.

**Comment by ysvenkat** [comment]
FYI, the below commits address the compilation issues:

https://github.com/globus/gsi-openssh/commit/516d21a0794d42680dc9e0d6788d8fd9c380b713
https://github.com/globus/gsi-openssh/commit/c4ebf3b1ad301653caf7eb66f7247f4fda406fa4

**Comment by ysvenkat** [comment]
A new pre-release of GSI-OpenSSH 7.3p1a is now available that includes the Fedora patch for compatibility with OpenSSL 1.1. Please test and let us know of any issues. Thanks.

https://github.com/globus/gsi-openssh/releases/tag/7.3p1a
